Phonet Class Reference
Phonet Class Reference
A Phonet is a vector of Phoneme objects responsible for creating the phonetic version of a word. Since Phonets consist of Phonemes, the Phonet will also hold the pronunciation of the word, suggested spellings for the word, and the class will be able to generate its own Phonets.
#include <Phonet.h>
Public Member Functions
Phonet ()
Defualt constructor for the Phonet. A Phonet will start with a min length of 2 and a max length of 10.
Phonet (std::vector< Phoneme > &, std::vector< Phoneme > &, unsigned)
Parameterized Constructor. The Phonet will be generated during the object creation. The Phonet will begin with a min length of 2 and a max length of ten.
Phonet (std::vector< Phoneme > &)
Parameterized constructor. Given a vector of Phonemes, a Phonet object will be created. The min and max lengths of the Phonet will be the size of the Phoneme vector.
~Phonet ()
Empty Phonet destructor.
void generate (std::vector< Phoneme > &, std::vector< Phoneme > &, unsigned)
Given a vector of both consonant and vowel Phonemes and a seed, a randomized phonet will be generated with the rules of the English phonetic alphabet. This is currently pretty screwy.
void print_phonet () const
Prints out the Phonemes in the constructed Phonet to console.
void print_pronunciation () const
Prints out an example of how the Phonet is supposed to be pronounced to console. The example will consist of multiple words printed in the correct order. Each word will consist of one Phoneme that is in the word generated.
Private Types
enum Phoneme_Type { CONSONANT = 0, VOWEL = 1 }
A Phoneme can only be two types, a consonant or a vowel. This is used to segment to the phoneme types in order to generate the Phonets.
Private Attributes
std::vector< Phoneme > m_phonemes
The vector containing all of the Phonemes responsible for creating the.
unsigned m_min_length
The minimum number of Phonemes that this Phonet can contain.
unsigned m_max_length
The maximum number of Phonemes that this Phonet can contain.
Friends
std::ostream & operator<< (std::ostream &os, const Phonet &rhs)
Overloads the output operator to print a Phonet to console. Only the Phonet itself will be printed, not the pronunciation or suggested spellings.
Detailed Description
A Phonet is a vector of Phoneme objects responsible for creating the phonetic version of a word. Since Phonets consist of Phonemes, the Phonet will also hold the pronunciation of the word, suggested spellings for the word, and the class will be able to generate its own Phonets.
Operations include:
Constructing an empty Phonet
Constructing a randomly generated Phonet
Constructing an already existing Phonet
Generating a random Phonet
Printing a Phonet to console
Printing a Phonets pronunciation to console
Printing a Phonet to console using << operator
Deprecated:
Phonets now use Phoneme class instead of std::string.
Bug:
The generation is terrible.
Definition at line 50 of file Phonet.h.
Member Enumeration Documentation
enum Phonet::Phoneme_Type private
A Phoneme can only be two types, a consonant or a vowel. This is used to segment to the phoneme types in order to generate the Phonets.
Members
CONSONANT
VOWEL
Definition at line 84 of file Phonet.h.
     {
       CONSONANT = 0,
       VOWEL = 1
     };
Constructor & Destructor Documentation
Phonet::Phonet (std::vector< Phoneme > & consonants, std::vector< Phoneme > & vowels, unsigned seed)
Parameterized Constructor. The Phonet will be generated during the object creation. The Phonet will begin with a min length of 2 and a max length of ten.
Parameters
consonants A reference to the vector of consonant Phonmes being used for the Phonet.
vowels A reference to the vector of vowel Phonemes being used for the Phonet.
seed The seed being used for the generator.
Definition at line 59 of file Phonet.cpp.
References generate().
                              :
 m_min_length(2),
 m_max_length(10)
 {
   generate(consonants, vowels, seed);
 }
Phonet::Phonet (std::vector< Phoneme > & phonemes)
Parameterized constructor. Given a vector of Phonemes, a Phonet object will be created. The min and max lengths of the Phonet will be the size of the Phoneme vector.
Parameters
phonemes The vector of strings containing the phonemes the Phonet will be initialized with.
Definition at line 81 of file Phonet.cpp.
References m_phonemes.
                                            :
 m_min_length(phonemes.size()),
 m_max_length(phonemes.size())
 {
   m_phonemes = phonemes;
 }
Member Function Documentation
void Phonet::generate (std::vector< Phoneme > & consonants, std::vector< Phoneme > & vowels, unsigned seed)
Given a vector of both consonant and vowel Phonemes and a seed, a randomized phonet will be generated with the rules of the English phonetic alphabet. This is currently pretty screwy.
Parameters
consonants The Vector of consonant Phonemes being used for the generation.
vowels The vector of vowel Phonemes being used for the gneneration.
seed The seed used for the random number generator.
Definition at line 113 of file Phonet.cpp.
References m_max_length, m_min_length, and m_phonemes.
Referenced by main(), and Phonet().
 {
   srand(seed);
   m_phonemes.clear();
   unsigned length = (rand() % (m_max_length - m_min_length + 1)) + m_min_length;
   Phoneme_Type type = static_cast<Phoneme_Type>(rand() % 2);
   while(length)
   {
     if(type)
     {
       unsigned vowel_index = rand() % vowels.size();
       m_phonemes.push_back(vowels[vowel_index]);
       type = static_cast<Phoneme_Type>(0);
     }
     else
     {
       unsigned consonant_index = rand() % consonants.size();
       m_phonemes.push_back(consonants[consonant_index]);
       type = static_cast<Phoneme_Type>(1);
     }
     --length;
   }
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Phonet & rhs) friend
Overloads the output operator to print a Phonet to console. Only the Phonet itself will be printed, not the pronunciation or suggested spellings.
Parameters
os The ostream the phonet will be sent to.
rhs The Phonet that is being sent to the ostream.
Returns
The ostream the Phonet was sent to.
Definition at line 205 of file Phonet.cpp.
 {
   rhs.print_phonet();
   return os;
 }
The documentation for this class was generated from the following files:
Phonet.h
Phonet.cpp