data_grab.cpp File Reference
data_grab.cpp File Reference
This file contains helper functions for grabbing phoneme data from file and organizing that phoneme data into the Phoneme class so it can be used by the PhonetGenerator. The phoneme data files can be found in data/.
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include "../header/Phoneme.h"
Functions
void read_file (std::vector< std::string > &vector, const char *file_name)
Reads in each line from a file into seperate elemnts of a provided vector.
void parse (std::vector< std::string > &storage, const std::string &data, const char delimiter)
Parses a line of string data by putting each set of string data between a specified delimiter into a vector. If the delimiter does not appear in the string provided, the vector will contain one element consisting of the whole string.
void parse_phoneme_data (std::string &phoneme, std::string &pronunciation, std::string &spellings, const std::string &data)
Given a line of phoneme file data, this function will seperate the different elemnts of the phoneme data in order to more easily create phonemes from the file data.
void create_phonemes (std::vector< Phoneme > &phonemes, const std::vector< std::string > &data)
A helper function that takes in the string data read from file and puts the data into Phonemes in order to use the Phonemes within a Phonet.
Detailed Description
This file contains helper functions for grabbing phoneme data from file and organizing that phoneme data into the Phoneme class so it can be used by the PhonetGenerator. The phoneme data files can be found in data/.
Author
Connor Deakin
E-mail: connortdeakin@gmail.com
Project: PhonetGenerator
Date
13/07/2016
Functions Include:
read_file
parse
parse_phoneme_data
create_phonemes
Deprecated:
create_phonemes parameters changed.
Definition in file data_grab.cpp.
Function Documentation
void create_phonemes (std::vector< Phoneme > & phonemes, const std::vector< std::string > & data)
A helper function that takes in the string data read from file and puts the data into Phonemes in order to use the Phonemes within a Phonet.
Parameters
phonemes All the Phoneme data will be stored in this vector of Phonemes.
data A vector of strings containing the phoneme data that was read from file.
Definition at line 152 of file data_grab.cpp.
References parse(), and parse_phoneme_data().
Referenced by main().
 {
   std::vector<std::string>::const_iterator phoneme_data;
   for(phoneme_data = data.begin(); phoneme_data != data.end(); ++phoneme_data)
   {
     std::string phoneme;
     std::string pronunciation;
     std::string spellings_str;
     parse_phoneme_data(phoneme, pronunciation, spellings_str, (*phoneme_data));
     std::vector<std::string> spellings;
     parse(spellings, spellings_str, (char)',');
     Phoneme new_phoneme(phoneme, pronunciation, spellings);
     phonemes.push_back(new_phoneme);
   }
 }
void parse (std::vector< std::string > & storage, const std::string & data, const char delimiter)
Parses a line of string data by putting each set of string data between a specified delimiter into a vector. If the delimiter does not appear in the string provided, the vector will contain one element consisting of the whole string.
Example If this was the data passed into the parse function (this/is/data), and the delimiter passed to the parse function was '/', the storage string vector would be filled with the follwing three elements.
this
is
data
Parameters
storage The parsed string data will be stored in this provided vector.
data This is the string that will be parsed and processed to be stored in the storage vector.
delimiter This is the delimiter that will be used to separate one vector element from another in the data string.
Definition at line 87 of file data_grab.cpp.
Referenced by create_phonemes().
 {
   size_t start = 0;
   size_t end = 0;
   end = data.find(delimiter, start);
   while(end != std::string::npos)
   {
     storage.push_back(data.substr(start, end - start));
     start = end + 1;
     end = data.find(delimiter, start);
   }
   storage.push_back(data.substr(start, data.size()));
 }
void parse_phoneme_data (std::string & phoneme, std::string & pronunciation, std::string & spellings, const std::string & data)
Given a line of phoneme file data, this function will seperate the different elemnts of the phoneme data in order to more easily create phonemes from the file data.
Parameters
phoneme The actual phoneme will be stored here.
pronunciation The string specifying the sound of the phoneme will be stored here.
spellings The string containing all of the possible spellings for the phoneme will be stored here.
data This is the string that contains the data from file to be parsed and put into the other string containers.
Definition at line 122 of file data_grab.cpp.
Referenced by create_phonemes().
   {
     size_t start = 0;
     size_t end = 0;
     end = data.find(':');
     phoneme = data.substr(start, end - start);
     start = end + 1;
     end = data.find(':',start);
     pronunciation = data.substr(start, end - start);
     start = end + 1;
     end = data.size();
     spellings = data.substr(start, end - start);
   }
void read_file (std::vector< std::string > & vector, const char * file_name)
Reads in each line from a file into seperate elemnts of a provided vector.
Parameters
vector A reference to the vector the file data will be pushed into.
file_name The name of the file being read into the vector reference.
Definition at line 44 of file data_grab.cpp.
Referenced by main().
 {
   std::ifstream file(file_name);
   if(!file.is_open())
     std::cout << "File [" << file_name << "] Not Opened" << std::endl;
   else
   {
     std::string line;
     std::getline(file, line);
     while(!file.eof())
     {
       vector.push_back(line);
       std::getline(file, line);
     }
   }
 }