main.cpp File Reference
main.cpp File Reference
Contains intitial code for the PhonetGenerator. This file is also currently responsible for reading in the phoneme and pronunciation data. This should eventually be segmented from this file.
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <ctime>
#include "../header/Phoneme.h"
#include "../header/Phonet.h"
Functions
void read_file (std::vector< std::string > &vector, const char *file_name)
Reads in each line from a file into seperate elemnts of a provided vector.
void create_phonemes (std::vector< Phoneme > &phonemes, std::vector< std::string > &sounds, std::vector< std::string > &examples)
A helper function that takes in the string data read from file and puts the data into Phonemes in order to use the Phonemes within a Phonet.
int main (int argc, char **argv)
Program start function. Currently responsible for reading in data and generating a phonet for printing.
Detailed Description
Contains intitial code for the PhonetGenerator. This file is also currently responsible for reading in the phoneme and pronunciation data. This should eventually be segmented from this file.
Author
Connor Deakin
E-mail: connortdeakin@gmail.com
Project: PhonetGenerator
Date
26/06/2016
Functions Include:
read_file
main
Definition in file main.cpp.
Function Documentation
void create_phonemes (std::vector< Phoneme > & phonemes, std::vector< std::string > & sounds, std::vector< std::string > & examples)
A helper function that takes in the string data read from file and puts the data into Phonemes in order to use the Phonemes within a Phonet.
Parameters
phonemes All the Phoneme data will be stored in this vector of Phonemes.
sounds A vector of strings in which the string data for a Phoneme is stored.
examples A vector of strings in which examples of pronunciations of the Phonemes are stored.
Definition at line 73 of file main.cpp.
Referenced by main().
 {
   std::vector<std::string>::iterator sound;
   std::vector<std::string>::iterator example;
   for(sound = sounds.begin(), example = examples.begin();
       sound != sounds.end() || example != examples.end();
       ++sound, ++example)
   {
     Phoneme phoneme(*sound, *example);
     phonemes.push_back(phoneme);
   }
 }
int main (int argc, char ** argv)
Program start function. Currently responsible for reading in data and generating a phonet for printing.
Parameters
argc The number of arguments provided on the command line (includes executable name)
argv An array of character arrays containing the strings provided on the command line.
Returns
Main Int
Definition at line 107 of file main.cpp.
References create_phonemes(), Phonet::generate(), Phonet::print_pronunciation(), and read_file().
 {
   std::vector<std::string> str_phoneme_consonant;
   std::vector<std::string> str_phoneme_vowel;
   std::vector<std::string> str_pronunciation_consonant;
   std::vector<std::string> str_pronunciation_vowel;
   read_file(str_phoneme_consonant, "../data/phoneme/consonant.txt");
   read_file(str_phoneme_vowel, "../data/phoneme/vowel.txt");
   read_file(str_pronunciation_consonant, "../data/pronunciation/consonant.txt");
   read_file(str_pronunciation_vowel, "../data/pronunciation/vowel.txt");
   std::vector<Phoneme> phonemes_consonants;
   std::vector<Phoneme> phonemes_vowels;
   create_phonemes(phonemes_consonants,
                   str_phoneme_consonant,
                   str_pronunciation_consonant);
   create_phonemes(phonemes_vowels,
                   str_phoneme_vowel,
                   str_pronunciation_vowel);
   Phonet phonet;
   phonet.generate(phonemes_consonants, phonemes_vowels, (unsigned)time(0));
   std::cout << phonet << std::endl;
   phonet.print_pronunciation();
   std::cout << std::endl;
   return 0;
 }
void read_file (std::vector< std::string > & vector, const char * file_name)
Reads in each line from a file into seperate elemnts of a provided vector.
Parameters
vector A reference to the vector the file data will be pushed into.
file_name The name of the file being read into the vector reference.
Definition at line 41 of file main.cpp.
Referenced by main().
 {
   std::ifstream file(file_name);
   if(!file.is_open())
     std::cout << "File [" << file_name << "] Not Opened" << std::endl;
   else
   {
     std::string line;
     std::getline(file, line);
     while(!file.eof())
     {
       vector.push_back(line);
       std::getline(file, line);
     }
   }
 }