PhonemePool Class Reference
PhonemePool Class Reference
This class is a wrapper around a vector of phonemes. It is only here to store a pool of existing phonemes that are read in from a phoneme file in the the constructor.
#include <PhonemePool.h>
Public Member Functions
PhonemePool (const char *phoneme_file)
Constructor for the PhonemePool. This will create a pool of phonemes using an existing phoneme config file for the generator.
const Phoneme * get_phoneme () const
Gets a randome Phoneme from the pool.
bool read_success () const
Returns true if the phoneme file was successfully read.
Private Member Functions
void extract_phoneme_data (const std::vector< std::string > &data, std::vector< size_t > &rule_starts)
Extracts all the phoneme data from text into phoneme objects. This function does not handle the parsing of the rules.
void extract_rule_data (const std::vector< std::string > &data, const std::vector< size_t > &rule_starts)
Extracts to rule data for phonemes from the raw phoneme data.
Phoneme * find_phoneme (const std::string &phoneme_string)
Will find a phoneme that exists within the pool using a string that contains the phoneme name.
Private Attributes
std::vector< Phoneme > m_phonemes
The vector of phonemes that the PhonemePool holds.
bool m_read_success
Identifies whether the phoneme file was successfully read or not.
Detailed Description
This class is a wrapper around a vector of phonemes. It is only here to store a pool of existing phonemes that are read in from a phoneme file in the the constructor.
Definition at line 31 of file PhonemePool.h.
Constructor & Destructor Documentation
PhonemePool()
PhonemePool::PhonemePool (const char * phoneme_file)
Constructor for the PhonemePool. This will create a pool of phonemes using an existing phoneme config file for the generator.
Parameters
phoneme_file The path to the file which all the phoneme data will be read from.
Definition at line 33 of file PhonemePool.cpp.
References extract_phoneme_data(), extract_rule_data(), m_read_success, and read_file().
                                                   : m_phonemes(),
   m_read_success(false)
 {
   std::vector<std::string> phoneme_data;
   read_file(phoneme_data, phoneme_file);
   std::vector<size_t> rule_starts;
   try
   {
     extract_phoneme_data(phoneme_data, rule_starts);
     extract_rule_data(phoneme_data, rule_starts);
     m_read_success = true;
   }
   catch(const std::string & error)
   {
     std::cout << "Error | " << error << std::endl;
   }
 }
Member Function Documentation
extract_phoneme_data()
void PhonemePool::extract_phoneme_data (const std::vector< std::string > & data, std::vector< size_t > & rule_starts) inline private
Extracts all the phoneme data from text into phoneme objects. This function does not handle the parsing of the rules.
Parameters
data The data that was read in from the phoneme config file.
rule_starts A vector that contains the idicies at which the rules for the phonemes begin. These indices refer to positions in the strings within the data parameter. This is only really crucial for extract_rule_data.
Definition at line 94 of file PhonemePool.cpp.
References m_phonemes.
Referenced by PhonemePool().
 {
   unsigned current_line = 1;
   std::vector<std::string>::const_iterator it = data.begin();
   std::vector<std::string>::const_iterator it_e = data.end();
   for(; it != it_e; ++it)
   {
     // saving line number into a string for errors
     char line_num_buffer[10];
     sprintf(line_num_buffer, "%d", current_line);
     std::string line_number(line_num_buffer);
     // extracting phonemes
     std::string phoneme;
     std::string example;
     std::string spellings;
     // start and end of a substring
     size_t start = 0;
     size_t end = 0;
     size_t distance = 0;
     // getting phoneme string
     end = it->find((char)':', start);
     // make sure there is an ending colon for the identifier
     if(end == std::string::npos)
     {
       std::string error("Line : ");
       error.append(line_number);
       error.append(" | Ending ':' for phoneme identifier not found");
       throw(error);
     }
     distance = end - start;
     phoneme = it->substr(start, distance);
     // getting example pronunciation
     start = end + 1;
     end = it->find((char)':', start);
     // make sure there is an ending colon for the pronunciation
     if(end == std::string::npos)
     {
       std::string error("Line : ");
       error.append(line_number);
       error.append(" | Ending ':' for phoneme pronunciation not found");
       throw(error);
     }
     example = it->substr(start, end - start);
     // getting spellings string
     start = end + 1;
     end = it->find((char)':', start);
     // make sure there is an ending colon for the spellings
     if(end == std::string::npos)
     {
       std::string error("Line : ");
       error.append(line_number);
       error.append(" | Ending ':' for phoneme spellings not found");
       throw(error);
     }
     spellings = it->substr(start, end - start);
     rule_starts.push_back(end + 1);
     // creating the new phoneme
     m_phonemes.push_back(Phoneme(phoneme, example, spellings, current_line));
     ++current_line;
   }
 }
extract_rule_data()
void PhonemePool::extract_rule_data (const std::vector< std::string > & data, const std::vector< size_t > & rule_starts) inline private
Extracts to rule data for phonemes from the raw phoneme data.
Parameters
data The raw phoneme data read from file.
rule_starts A vector that contains the idicies at which the rules for the phonemes begin. These indices refer to positions in the strings within the data parameter.
Definition at line 171 of file PhonemePool.cpp.
References find_phoneme(), and m_phonemes.
Referenced by PhonemePool().
 {
   unsigned current_phoneme = 0;
   while(current_phoneme < m_phonemes.size())
   {
     size_t start = rule_starts[current_phoneme];
     size_t end = rule_starts[current_phoneme];
     if(start >= data.size())
     {
       ++current_phoneme;
       continue;
     }
     end = data[current_phoneme].find(',', start);
     while(end != std::string::npos)
     {
       // clean this up a little
       std::string new_rule_str = data[current_phoneme].substr(start,
                                                               end - start);
       Phoneme * new_rule = find_phoneme(new_rule_str);
       if(new_rule)
         m_phonemes[current_phoneme].add_rule(new_rule);
       start = end + 1;
       end = data[current_phoneme].find(',', start);
     }
     std::string new_rule_str =
       data[current_phoneme].substr(start, data.size() - start);
     Phoneme * new_rule = find_phoneme(new_rule_str);
     if(new_rule)
       m_phonemes[current_phoneme].add_rule(new_rule);
     ++current_phoneme;
   }
 }
find_phoneme()
Phoneme * PhonemePool::find_phoneme (const std::string & phoneme_string) private
Will find a phoneme that exists within the pool using a string that contains the phoneme name.
Parameters
phoneme_string The string that contains the phoneme name.
Returns
If the Phoneme is found, a pointer to the Phoneme object is returned. If not, an exception will be thrown.
Definition at line 221 of file PhonemePool.cpp.
References m_phonemes.
Referenced by extract_rule_data().
 {
   std::vector<Phoneme>::iterator it = m_phonemes.begin();
   std::vector<Phoneme>::iterator it_e = m_phonemes.end();
   for(; it != it_e; ++it)
   {
     if((*it) == phoneme_string)
       return &(*it);
   }
   // YOU SHOULD PROBABLY THROUGH AN EXCEPTION OR SOMEthing HERE
   return NULL;
 }
get_phoneme()
const Phoneme * PhonemePool::get_phoneme () const
Gets a randome Phoneme from the pool.
Returns
A random Phoneme from the pool.
Definition at line 60 of file PhonemePool.cpp.
References m_phonemes.
Referenced by Phonet::generate().
 {
   long unsigned phoneme_index = rand() % m_phonemes.size();
   return &(m_phonemes[phoneme_index]);
 }
read_success()
bool PhonemePool::read_success () const
Returns true if the phoneme file was successfully read.
Returns
Look at brief.
Definition at line 74 of file PhonemePool.cpp.
References m_read_success.
 {
   return m_read_success;
 }
The documentation for this class was generated from the following files:
PhonemePool.h
PhonemePool.cpp