Options Class Reference
Options Class Reference
This Options class is specific to the PhonetGenerator. Given argc and argv, the constructor for this class will use getopt to parse the command line and configure the Options object's members to the proper values. Those members are various configurations used for the PhonetGenerator.
#include <Options.h>
Public Member Functions
Options (int, char **)
Parameterized constructor for the Options class. This is the classes only constructor. This constructor will also set the defaults for the Options object's members.
~Options ()
Destructor for the Options class.
size_t get_min_length ()
Gets the value of m_min_length.
size_t get_max_length ()
Gets the value of m_max_length.
unsigned get_num_words ()
Gets the value of m_num_words.
unsigned get_num_spellings ()
Gets the value of m_num_spellings.
bool get_pronunciation ()
Gets the value of m_pronunciation.
unsigned get_seed ()
Gets the value of the random seed.
const std::string & get_phoneme_file ()
Returns the name of the phoneme data file to be used by the generator.
bool get_help ()
Returns whether the help text should be printed or not.
Static Public Member Functions
static void print_help ()
Prints out the help interface for the PhonetGenerator's switches.
Private Member Functions
void parse_options (int, char **)
This is responsible for parsing the functions from argc and argv and ajdusting the PhonetGenerator's configurations using getopt.
Private Attributes
size_t m_min_length
The minimum number of Phonemes that can be in a Phonet.
size_t m_max_length
The maximum number of Phonemes that can be in a Phonet.
unsigned m_num_words
The number of Phonets that will be generated.
unsigned m_num_spellings
The number of spellings that will be generated for each of the Phonets.
bool m_pronunciation
Determines whether the Phonets' pronunciations will be printed or not.
unsigned m_seed
The seed used for the PhonetGenerator's randomization.
std::string m_phoneme_file
The file that all the phoneme data will be loaded from.
bool m_help
Used to identify whether the help text should be printed.
Detailed Description
This Options class is specific to the PhonetGenerator. Given argc and argv, the constructor for this class will use getopt to parse the command line and configure the Options object's members to the proper values. Those members are various configurations used for the PhonetGenerator.
Operations include:
Creating the Options object.
Getting all members of the Options object through getters.
Printing out the help interface for the PhonetGenerator's switches.
Deprecated:
Nothing
Bug:
Nothing
Definition at line 37 of file Options.h.
Constructor & Destructor Documentation
Options()
Options::Options (int argc, char ** argv)
Parameterized constructor for the Options class. This is the classes only constructor. This constructor will also set the defaults for the Options object's members.
Defautls
m_min_length = 2
m_max_length = 10
m_num_words = 1
m_num_spellings = 0
m_pronunciation = false
m_seed = time(0)
m_phoneme_file = "config/english_vcvc.phoneme"
Parameters
argc The argc from main.
argv The argv from main.
Definition at line 55 of file Options.cpp.
References m_seed, and parse_options().
                                       : m_min_length(2), m_max_length(10),
 m_num_words(1), m_num_spellings(0), m_pronunciation(false),
 m_phoneme_file("Config/english_default.phoneme"), m_help(false)
 {
   m_seed = (unsigned)time(0);
   parse_options(argc, argv);
 }
Member Function Documentation
get_help()
bool Options::get_help ()
Returns whether the help text should be printed or not.
Returns
If the help text should be printed, true.
Definition at line 248 of file Options.cpp.
References m_help.
Referenced by main().
 { return m_help; }
get_max_length()
size_t Options::get_max_length ()
Gets the value of m_max_length.
Returns
The value of m_max_length.
Definition at line 185 of file Options.cpp.
References m_max_length.
Referenced by main().
 { return m_max_length; }
get_min_length()
size_t Options::get_min_length ()
Gets the value of m_min_length.
Returns
The value of m_min_length.
Definition at line 174 of file Options.cpp.
References m_min_length.
Referenced by main().
 { return m_min_length; }
get_num_spellings()
unsigned Options::get_num_spellings ()
Gets the value of m_num_spellings.
Returns
The value of m_num_spellings.
Definition at line 207 of file Options.cpp.
References m_num_spellings.
Referenced by main().
 { return m_num_spellings; }
get_num_words()
unsigned Options::get_num_words ()
Gets the value of m_num_words.
Returns
The value of m_num_words.
Definition at line 196 of file Options.cpp.
References m_num_words.
Referenced by main().
 { return m_num_words; }
get_phoneme_file()
const std::string & Options::get_phoneme_file ()
Returns the name of the phoneme data file to be used by the generator.
Returns
The phoneme config file name.
Definition at line 238 of file Options.cpp.
References m_phoneme_file.
Referenced by main().
 { return m_phoneme_file; }
get_pronunciation()
bool Options::get_pronunciation ()
Gets the value of m_pronunciation.
Returns
The value of m_pronunciation.
Definition at line 218 of file Options.cpp.
References m_pronunciation.
Referenced by main().
 { return m_pronunciation; }
get_seed()
unsigned Options::get_seed ()
Gets the value of the random seed.
Returns
The random seed value.
Definition at line 228 of file Options.cpp.
References m_seed.
Referenced by main().
 { return m_seed; }
parse_options()
void Options::parse_options (int argc, char ** argv) private
This is responsible for parsing the functions from argc and argv and ajdusting the PhonetGenerator's configurations using getopt.
Parameters
argc The argc from main.
argv The argv from main.
Definition at line 85 of file Options.cpp.
References m_help, m_max_length, m_min_length, m_num_spellings, m_num_words, m_phoneme_file, m_pronunciation, and m_seed.
Referenced by Options().
 {
   bool error = false;
   int opt;
   while(1)
   {
     int opt_index = 0;
     static struct option long_options[] =
     {
       {"minimum-length", required_argument, NULL, 'n'},
       {"maximum-length", required_argument, NULL, 'x'},
       {"words",          required_argument, NULL, 'w'},
       {"spellings",      required_argument, NULL, 's'},
       {"pronunciation",  no_argument,       NULL, 'p'},
       {"seed",           required_argument, NULL, 'r'},
       {"file",           required_argument, NULL, 'f'},
       {"help",           no_argument,       NULL, 'h'}
     };
     opt = getopt_long(argc, argv, ":n:x:w:s:ps:r:f:h", long_options, &opt_index);
     if(opt == -1)
       break;
     switch (opt)
     {
       case 'n': m_min_length = atoi(optarg);     break;
       case 'x': m_max_length = atoi(optarg);     break;
       case 'w': m_num_words = atoi(optarg);      break;
       case 's': m_num_spellings = atoi(optarg);  break;
       case 'p': m_pronunciation = true;          break;
       case 'r': m_seed = (unsigned)atoi(optarg); break;
       case 'f': m_phoneme_file = optarg;         break;
       case 'h': m_help = true;                   break;
       case '?': std::cout << "The provided option [" << (char)optopt
                           << "] is not an option." << std::endl;
                 error = true; break;
       case ':': std::cout << "The provided option [" << (char)optopt
                           << "] requires an argument." << std::endl;
                 error = true; break;
     }
   }
   if(error)
     std::cout << "Use -h or --help to see all options and how they are used."
               << std::endl;
 }
The documentation for this class was generated from the following files:
Options.h
Options.cpp